### ISSUE TITLE
Problem with service bus registration when running from NUnit+ReSharper

### ISSUE THREAD

**Issue by claytona-armstrong5** [Shuttle/Shuttle.Core.Infrastructure#5]
Hi,

I'm in the progress of upgrading to V8, and am getting an exception when trying to run unit tests.
The exception occurs when trying to run "ServiceBus.Register", which I'm calling to register the dependencies for the bus.  (We are using both Autofac and Castle in different systems, but that does not make any difference)

The exception is:

`System.ArgumentNullException : Value cannot be null.
Parameter name: path
   at System.IO.Directory.GetDirectories(String path)
   at Shuttle.Core.Infrastructure.ReflectionService.GetAssembliesRecursive(String folder)
   at Shuttle.Core.Infrastructure.ReflectionService.GetAssemblies()
   at Shuttle.Core.Infrastructure.ReflectionService.GetTypes(Type type)
   at Shuttle.Core.Infrastructure.ComponentRegistryExtensions.RegistryBoostrap(IComponentRegistry registry)
   at Shuttle.Esb.ServiceBus.Register(IComponentRegistry registry, IServiceBusConfiguration configuration)
   at Shuttle.Esb.ServiceBus.Register(IComponentRegistry registry)
   at Racti.Pure.WindowsService.Core.Shared.Installer.Install(IWindsorContainer container, IConfigurationStore store) in E:\Dev\IS\ForCCPayments\src\WindowsService.Core\Shared\Installer.cs:line 28
   at Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers, DefaultComponentInstaller scope)
   at Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers)
   ...
`

The problem seems to be in Shuttle.Core.Infrastructure.ReflectionService.GetAssemblies()
That method seems to assume that if "ShadowCopyFiles" is true on the current application domain, then the "DynamicDirectory" property on the appdomain will have a non-null value. 
This is not the case when I tried to run a unit test that uses the bus. ShadowCopyFiles is true, but the DynamicDirectory is null.  

My test is using NUnit 3.5, and I'm running it using ReSharper 2016
I'm not sure if it's NUnit or ReSharper that would be setting up the AppDomain... I'm guessing NUnit

Is this a known problem?  Or am I likely doing something silly?

Thanks in advance!

**Comment by claytona-armstrong5** [comment]
Some more information on this...

I believe NUnit had a change in V3 that made shadow copying be enabled by default.
And there is an option in ReSharper to disable shadow copy. I've tried turning that option on, and it seems to work.. the exception above no longer occurs.

If possible I'd prefer that our team did not need a non-default configuration of ReSharper.  Disabling ShadowCopy means that you cannot compile while tests are running.

Would still be interested to know if this is a considered something needing a fix

Thanks

**Comment by eben-roux** [comment]
Thanks for letting me know.  I do not use the shadow copy on Resharper since I have picked up a couple of issue w.r.t. my tests.  But yes, it is certainly Resharper setting the `AppDomain` property.

I guess that if the `DynamicDirectory` is empty I go back to working as if shadow copy is set to false.

**Comment by eben-roux** [comment]
I have created a new release:

- https://github.com/Shuttle/Shuttle.Core.Infrastructure/releases/tag/v8.0.2

Let me know if this helps.  Effectively ignoring shadow copies if there is no dynamic directory.

Please let me know if this solves your issue.

**Comment by claytona-armstrong5** [comment]
Fantastic, many thanks for your very prompt response.
Yes, I've taken the update, and that does resolve the problem.

Many thanks!
